name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: cd frontend; npm install;
      - run: npm test
